name: CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover tests/

    - name: Generate coverage report
      run: |
        coverage report -m

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/project2-image:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/project2-image:latest

    - name: Clone Hugging Face Space repository
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git clone https://huggingface.co/spaces/HotCuppaJoJo/Retro-Corner-Feature-Detector_Moravec-Harris_with_LBP-HOG
        cd Retro-Corner-Feature-Detector_Moravec-Harris_with_LBP-HOG
        git remote set-url origin https://username:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/HotCuppaJoJo/Retro-Corner-Feature-Detector_Moravec-Harris_with_LBP-HOG

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_NAME }}"

    - name: Update Docker image in Hugging Face Space
      run: |
        echo 'FROM ${{ secrets.DOCKER_HUB_USERNAME }}/project2-image:latest' > Retro-Corner-Feature-Detector_Moravec-Harris_with_LBP-HOG/Dockerfile
        cd Retro-Corner-Feature-Detector_Moravec-Harris_with_LBP-HOG
        git add Dockerfile
        git commit -m "Update Docker image" || echo "No changes to commit"
        git push origin main